# This file is managed by Qt Creator, do not edit!

set("CMAKE_GENERATOR" "Ninja" CACHE "STRING" "" FORCE)
set("CMAKE_BUILD_TYPE" "Debug" CACHE "STRING" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "D:/Qt/5.15.2/msvc2019_64/bin/qmake.exe" CACHE "FILEPATH" "" FORCE)
set("CMAKE_PREFIX_PATH" "D:/Qt/5.15.2/msvc2019_64" CACHE "PATH" "" FORCE)
set("CMAKE_C_COMPILER" "" CACHE "FILEPATH" "" FORCE)
set("CMAKE_CXX_COMPILER" "" CACHE "FILEPATH" "" FORCE)
set("CMAKE_CXX_FLAGS_INIT" "-DQT_QML_DEBUG" CACHE "STRING" "" FORCE)