/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109420-g262e7439c6-20221214"
#endif /* AVUTIL_FFVERSION_H */
